name: Build and Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install cppcheck static analysis
      run: sudo apt-get update && sudo apt-get install -y cppcheck
      
    - name: build
      run: g++ -Wall -Wextra -Werror --coverage -o senderExe sender/*.cpp
      
    - name: build Receiver
      run: g++ -Wall -Wextra -Werror --coverage -o receiverExe receiver/receiver.cpp  
      
    - name: static analysis
      run: cppcheck --suppress=missingIncludeSystem --check-config --force --enable=all --error-exitcode=1 .
      
    - name: run
      run: ./senderExe sample-review/review-report.csv 2 | ./receiverExe
    
    - name: receiver coverage report
      run: gcov -r receiver.cpp
    
    - name: sender coverage report
      run: gcov -r Sendermain.cpp
